name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.3
        with:
          host: "191.252.181.250"
          username: "root"
          password: "Renato@96475870"
          source: "."
          target: "/root/home"

      - name: "Build da aplicação node"
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: "191.252.181.250"
          username: "root"
          password: "Renato@96475870"
          script: |
            cd /root/home
            ls -la
            npm install
          
        