name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy via FTP on VPS"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 191.252.181.250
          username: root
          password: "Renato@96475870"
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /home/
          exclude: |
            **/node_modules/**
            **/package-lock.json

          
        