name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 191.252.181.250
        username: deployuser
        password: "Renato@96475870"
        source: ./
        target: /home/deployuser/
        script: |
          cd /home/deployuser/
          ls -la
          npm install
          npm run build
          npm run start
        