name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          password: "Renato@96475870"
          SOURCE: "./"
          TARGET: "/var/www/my-app"
          REMOTE_HOST: 191.252.181.250
          REMOTE_USER: deployuser
          # Optional: Add port if not 22
          # REMOTE_PORT: 2222
          ARGS: "-rltgoDzvO --delete" # Example rsync arguments

      - name: Execute remote command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 191.252.181.250
          username: deployuser
          password: "Renato@96475870"
          port: 22
          script: |
            cd /var/www/my-app
            ls -la
            npm install