name: Node.js CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Baixar o repositório"
      - uses: actions/checkout@v4 # Checkout the repository
      - name: "Instalar o Node.js"
       # - name "Copiar arquivos para VPS"
       # uses: actions/scp-action@v0.1.7
       # with:
       # host: ${{ secrets.HOST }}
       # username: ${{ secrets.USERNAME }}
       # password: ${{ secrets.PASSWORD }}
       # port: ${{ secrets.PORT }}
       # source: "."
       # target: "/sistema"
       # - name: "Build da aplicação"
       #   uses: appleboy/ssh-action@v1.0.3
       #   with:
       #     host: ${{ secrets.HOST }}
       #     username: ${{ secrets.USERNAME }}
       #     password: ${{ secrets.PASSWORD }}
       #     script: |
       #       cd /sistema
       #       npm install
       #       npm run build
       #       npm run test

        uses: actions/setup-node@v4 # Set up Node.js
        with:
          node-version: 22. # Set the Node.js version
      - name: Install dependencies
        run: npm install
      - name: run install, build and start
        run: npm start
        # run: |
        #   npm install
        #   npm run build
        #   npm run test
        