name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 191.252.181.250
          username: deployuser
          password: "Renato@96475870"
          port: 22
          source: "./"
          target: "/home/deployuser/"
          overwrite: true

      - name: Execute remote command
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 191.252.181.250
          username: deployuser
          password: "Renato@96475870"
          port: 22
          script: |
            cd /home/deployuser/
            ls -la
            npm install
