name: Node.js CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

        
      - nameListar arquivos
      run: find . -print

      - name: "Build da aplicação node"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          host: "191.252.181.250"
          username: "root"
          password: "Renato@96475870"
          local_dir: "."
          remote_dir: "/home"
          delete: true
          clean: true
        exclude: "node_modules,package-lock.json"

          
        